# Generated by Django 4.0.5 on 2022-06-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_qna_modified_date_alter_qna_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
