# Generated by Django 4.0.5 on 2022-06-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_qna_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
