# Generated by Django 4.0.5 on 2022-06-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_alter_qna_answer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='answer_date',
        ),
    ]
