# Generated by Django 4.0.5 on 2022-06-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
